/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paqueteria;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author grifiun
 */
public class MenuAdministrador extends javax.swing.JFrame {
    EnlaceJDBC enlace = new EnlaceJDBC();
    int codRutaTemporal;
    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador() {
        initComponents();
        destinosDisponibles.setVisible(false);
        desactivarPaneles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        btnCrearRutas = new javax.swing.JButton();
        btnModificarRutas = new javax.swing.JButton();
        btnCrearDestinos = new javax.swing.JButton();
        btnModificarDestinos = new javax.swing.JButton();
        btnModificarTarifaGlobal = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        lblCajaTexto2 = new javax.swing.JLabel();
        cajaTextoDato2 = new javax.swing.JTextField();
        lblCajaTexto1 = new javax.swing.JLabel();
        cajaTextoDato1 = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        cajaTextoDato3 = new javax.swing.JTextField();
        lblCajaTexto3 = new javax.swing.JLabel();
        destinosDisponibles = new javax.swing.JComboBox<>();
        lblTitulo2 = new javax.swing.JLabel();
        panelModificarRutas = new javax.swing.JPanel();
        comboBoxPuntosControl = new javax.swing.JComboBox<>();
        cajaTextoNuevaTarifaPControl = new javax.swing.JTextField();
        lblNuevoNombreRuta = new javax.swing.JLabel();
        lblNuevaTarifaPuntoControl = new javax.swing.JLabel();
        btnGuardarNombre = new javax.swing.JButton();
        cajaTextoNuevoNombrePControl = new javax.swing.JTextField();
        cajaTextoNuevoNombreRuta = new javax.swing.JTextField();
        NuevoNombrePuntoControl = new javax.swing.JLabel();
        lblCodigoPControl = new javax.swing.JLabel();
        btnGuardarCambios = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setSize(new java.awt.Dimension(1200, 800));

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        lblTitulo.setText("MENU ADMINISTRADOR");

        btnCrearRutas.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCrearRutas.setText("Crear rutas");
        btnCrearRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRutasActionPerformed(evt);
            }
        });

        btnModificarRutas.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnModificarRutas.setText("Modificar rutas");
        btnModificarRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarRutasActionPerformed(evt);
            }
        });

        btnCrearDestinos.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnCrearDestinos.setText("Crear destinos");
        btnCrearDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDestinosActionPerformed(evt);
            }
        });

        btnModificarDestinos.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnModificarDestinos.setText("Modificar destinos");
        btnModificarDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDestinosActionPerformed(evt);
            }
        });

        btnModificarTarifaGlobal.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnModificarTarifaGlobal.setText("Modificar tarifa global");
        btnModificarTarifaGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarTarifaGlobalActionPerformed(evt);
            }
        });

        btnReportes.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnReportes.setText("Crear Usuarios");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificarTarifaGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(btnModificarRutas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearRutas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearDestinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarDestinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrearRutas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarRutas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrearDestinos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarDestinos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarTarifaGlobal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatos.setMaximumSize(new java.awt.Dimension(10, 10));
        panelDatos.setMinimumSize(new java.awt.Dimension(1200, 800));

        lblCajaTexto2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCajaTexto2.setText("Ingresar codigo de ruta:");

        lblCajaTexto1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCajaTexto1.setText("Nombre de la ruta:");

        btnAtras.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnAtras.setText("atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnGuardar.setText("siguiente");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnAgregar.setText("agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblCajaTexto3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCajaTexto3.setText("jLabel1");

        destinosDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCajaTexto2)
                    .addComponent(lblCajaTexto1)
                    .addComponent(lblCajaTexto3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajaTextoDato3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cajaTextoDato2)
                    .addComponent(cajaTextoDato1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destinosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaTextoDato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCajaTexto3)
                    .addComponent(destinosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCajaTexto2)
                        .addComponent(cajaTextoDato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaTextoDato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCajaTexto1))
                        .addGap(34, 34, 34)))
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitulo2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo2.setText("CREAR RUTAS");

        comboBoxPuntosControl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNuevoNombreRuta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblNuevoNombreRuta.setText("Nuevo nombre ruta:");

        lblNuevaTarifaPuntoControl.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblNuevaTarifaPuntoControl.setText("Nueva tarifa punto de control:");

        btnGuardarNombre.setText("guardar nombre");
        btnGuardarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNombreActionPerformed(evt);
            }
        });

        NuevoNombrePuntoControl.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        NuevoNombrePuntoControl.setText("Nuevo nombre punto de control:");

        lblCodigoPControl.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCodigoPControl.setText("codigo de punto de control a modificar:");

        btnGuardarCambios.setText("guardar cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        btnSalir.setText("salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModificarRutasLayout = new javax.swing.GroupLayout(panelModificarRutas);
        panelModificarRutas.setLayout(panelModificarRutasLayout);
        panelModificarRutasLayout.setHorizontalGroup(
            panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarRutasLayout.createSequentialGroup()
                .addGroup(panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarRutasLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNuevoNombreRuta)
                            .addComponent(NuevoNombrePuntoControl)
                            .addComponent(lblNuevaTarifaPuntoControl)))
                    .addGroup(panelModificarRutasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCodigoPControl)))
                .addGroup(panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelModificarRutasLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(cajaTextoNuevaTarifaPControl, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarRutasLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelModificarRutasLayout.createSequentialGroup()
                                        .addComponent(comboBoxPuntosControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGuardarCambios))
                                    .addComponent(cajaTextoNuevoNombrePControl, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGuardarNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarRutasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(cajaTextoNuevoNombreRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelModificarRutasLayout.setVerticalGroup(
            panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaTextoNuevoNombreRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevoNombreRuta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarRutasLayout.createSequentialGroup()
                        .addComponent(btnGuardarNombre)
                        .addGap(11, 11, 11)
                        .addGroup(panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaTextoNuevaTarifaPControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNuevaTarifaPuntoControl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaTextoNuevoNombrePControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NuevoNombrePuntoControl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarCambios)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(panelModificarRutasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelModificarRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxPuntosControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigoPControl))))
                .addComponent(btnSalir)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo)
                        .addGap(312, 312, 312))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(panelModificarRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 72, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 799, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(lblTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelModificarRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(622, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRutasActionPerformed
        // TODO add your handling code here:
        destinosDisponibles.setVisible(true);
        modificarEstadoBotonesPanelOpciones(false);
        activarComponentesPanelDatos(true, true, true, true, true, true, true, true, false);
        panelDatos.setVisible(true);
        lblTitulo2.setText("CREAR RUTAS");
        establecerTextosCrearRutaParte1();
            ArrayList<String> listaDestinos = enlace.destinosDisp();
            destinosDisponibles.removeAllItems();
            
            for(int i = 0; i < listaDestinos.size(); i++){
                destinosDisponibles.addItem(listaDestinos.get(i));
            }  
    }//GEN-LAST:event_btnCrearRutasActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        String textoBoton = btnGuardar.getText();
        String titulo2 = lblTitulo2.getText();
        
        if(titulo2 == "CREAR RUTAS" || titulo2 == "MODIFICAR RUTAS" || titulo2 == "CREAR DESTINOS" || titulo2 == "MODIFICAR DESTINOS" || titulo2 == "MODIFICAR TARIFA GLOBAL"){
            panelDatos.setVisible(false);            
            modificarEstadoBotonesPanelOpciones(true);
            lblTitulo2.setVisible(false);
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String textoBoton = btnGuardar.getText();
        String titulo2 = lblTitulo2.getText();

        if(titulo2 == "CREAR RUTAS"){      
                      
            
            if(ManejadorError.verificarCampo(cajaTextoNuevaTarifaPControl.getText()) && ManejadorError.verificarCampo(cajaTextoDato2.getText())){
                try{
                    int codRuta = Integer.parseInt(cajaTextoDato2.getText());
                    String nombreRuta = cajaTextoDato1.getText();
                    int codDestino = Integer.parseInt((String) destinosDisponibles.getSelectedItem());
                    codRutaTemporal = codRuta;
                    enlace.crearRutas(codRuta, nombreRuta, codDestino);                    
                    btnAgregar.setVisible(true);
                    
                    cambiarTextoLabelsDatos("Nombre del punto de control:", "Ingresar codigo del punto de control:", "cantidad cola:");
                    cambiarTextoBtnGuardar("guardar ruta");                    
                    btnAtras.setVisible(false);
                    lblTitulo2.setText("AGREGAR PUNTOS DE CONTROL");
                    cajaTextoDato3.setVisible(true);
                    destinosDisponibles.setVisible(false);                    
                    JOptionPane.showMessageDialog(this, MensajesErrores.DATOS_GUARDADOS);
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, MensajesErrores.NO_SON_NUMEROS);                
                }
            }else{
                JOptionPane.showMessageDialog(this, MensajesErrores.DATOS_FALTANTES);
            }
            
            
            
            
        }
        if(titulo2 == "AGREGAR PUNTOS DE CONTROL"){       
                    modificarEstadoBotonesPanelOpciones(true);
                    panelDatos.setVisible(false); 
                    btnAtras.setVisible(true);
                    lblTitulo2.setVisible(false);                           
                 
            
            
        }
        if(titulo2 == "MODIFICAR RUTAS"){
            panelModificarRutas.setVisible(true);
            panelDatos.setVisible(false);
            
            ArrayList<String> listaPC = enlace.destinosDisp();
            comboBoxPuntosControl.removeAllItems();
            
            for(int i = 0; i < listaPC.size(); i++){
                comboBoxPuntosControl.addItem(listaPC.get(i));
            }  
            
             if(ManejadorError.verificarCampo(cajaTextoDato2.getText())){
                try{
                    int codR = Integer.parseInt(cajaTextoDato2.getText());
                    codRutaTemporal = codR;
                    modificarEstadoBotonesPanelOpciones(true);
                    panelDatos.setVisible(false); 
                    lblTitulo2.setVisible(false);
                    
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, MensajesErrores.NO_SON_NUMEROS);                }
            }else{
                JOptionPane.showMessageDialog(this, MensajesErrores.DATOS_FALTANTES);
            }  
            
            
        }
        if(titulo2 == "CREAR DESTINOS"){            
             
            if(ManejadorError.verificarCampo(cajaTextoDato1.getText()) && ManejadorError.verificarCampo(cajaTextoDato2.getText()) && ManejadorError.verificarCampo(cajaTextoDato3.getText())){
                try{
                    int codDest = Integer.parseInt(cajaTextoDato1.getText());
                    String nombreDest = cajaTextoDato3.getText();
                    int tarifa = Integer.parseInt(cajaTextoDato2.getText());
                    enlace.crearDestino(codDest, nombreDest, tarifa);
                    modificarEstadoBotonesPanelOpciones(true);
                    panelDatos.setVisible(false); 
                    lblTitulo2.setVisible(false);
                    JOptionPane.showMessageDialog(this, MensajesErrores.DATOS_GUARDADOS);
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, MensajesErrores.NO_SON_NUMEROS);                }
            }else{
                JOptionPane.showMessageDialog(this, MensajesErrores.DATOS_FALTANTES);
            }  
                     
            
        }  
        if(titulo2 == "MODIFICAR DESTINOS"){
            modificarEstadoBotonesPanelOpciones(true);
            panelDatos.setVisible(false); 
            lblTitulo2.setVisible(false);
        }  
        if(titulo2 == "MODIFICAR TARIFA GLOBAL"){
            
            String texto = cajaTextoDato1.getText();
            if(texto.equals(""))
                JOptionPane.showMessageDialog(this, MensajesErrores.DATOS_FALTANTES);
            else{
                modificarEstadoBotonesPanelOpciones(true);
                panelDatos.setVisible(false); 
                lblTitulo2.setVisible(false);
                modificarTarifaGlobal(Integer.parseInt(cajaTextoDato1.getText()));
                JOptionPane.showMessageDialog(this, MensajesErrores.DATOS_GUARDADOS);
            }
            
        } 
        cajaTextoDato1.setText("");
        cajaTextoDato2.setText("");
        cajaTextoDato3.setText("");
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    
    private void establecerTextosCrearRutaParte1(){
        btnAgregar.setVisible(false);
        cambiarTextoLabelsDatos("Nombre de la ruta:", "Ingresar codigo de ruta:", "Destino de la ruta:");
        cambiarTextoBtnGuardar("siguiente");
    }
    
    private void cambiarTextoLabelsDatos(String textoLabel1, String textoLabel2, String textoLabel3){
        lblCajaTexto1.setText(textoLabel1);
        lblCajaTexto2.setText(textoLabel2);
        lblCajaTexto3.setText(textoLabel3);
    }
    
    private void cambiarTextoBtnGuardar(String textoBtnGuardar){
        btnGuardar.setText(textoBtnGuardar);
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(ManejadorError.verificarCampo(cajaTextoDato1.getText()) && ManejadorError.verificarCampo(cajaTextoDato2.getText()) && ManejadorError.verificarCampo(cajaTextoDato3.getText())){
                try{
                    int codPC = Integer.parseInt(cajaTextoDato2.getText());
                    String nombrePC = cajaTextoDato1.getText();
                    int cola = Integer.parseInt(cajaTextoDato3.getText());
                    enlace.crearPuntoControl(codPC, codRutaTemporal, nombrePC, cola);                    
                                             
                    JOptionPane.showMessageDialog(this, MensajesErrores.DATOS_GUARDADOS);
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, MensajesErrores.NO_SON_NUMEROS);                }
            }else{
                JOptionPane.showMessageDialog(this, MensajesErrores.DATOS_FALTANTES);
            }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarRutasActionPerformed
        // TODO add your handling code here:
        activarComponentesPanelDatos(false, true, true, false, true, false, false, true, false);
        modificarEstadoBotonesPanelOpciones(false);
        panelDatos.setVisible(true);
        lblTitulo2.setText("MODIFICAR RUTAS");
        btnGuardar.setText("modificar ruta");
        lblCajaTexto2.setText("Ingresar codigo ruta:");
    }//GEN-LAST:event_btnModificarRutasActionPerformed

    private void btnCrearDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDestinosActionPerformed
        // TODO add your handling code here:
        panelDatos.setVisible(true);
        activarComponentesPanelDatos(false, true, true, true, true, true, true, true, true);
        modificarEstadoBotonesPanelOpciones(false);
        btnGuardar.setText("guardar");
        cambiarTextoLabelsDatos("Codigo destino", "Tarifa destino", "Nombre destino:");
        lblTitulo2.setText("CREAR DESTINOS");
    }//GEN-LAST:event_btnCrearDestinosActionPerformed

    private void btnModificarDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDestinosActionPerformed
        // TODO add your handling code here:
        panelDatos.setVisible(true);
        activarComponentesPanelDatos(false, true, true, true, true, true, true, true, true);
        modificarEstadoBotonesPanelOpciones(false);
        btnGuardar.setText("guardar");
        cambiarTextoLabelsDatos("Codigo destino", "Nueva tarifa destino", "Nuevo nombre destino:");
        lblTitulo2.setText("MODIFICAR DESTINOS");
    }//GEN-LAST:event_btnModificarDestinosActionPerformed

    private void btnModificarTarifaGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarTarifaGlobalActionPerformed
        // TODO add your handling code here:
        panelDatos.setVisible(true);
        activarComponentesPanelDatos(false, true, true, true, false, false, true, false, false);
        modificarEstadoBotonesPanelOpciones(false);
        btnGuardar.setText("guardar");
        cambiarTextoLabelsDatos("Nueva tarifa global:", "", "");
        lblTitulo2.setText("MODIFICAR TARIFA GLOBAL");
    }//GEN-LAST:event_btnModificarTarifaGlobalActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        VentanaReportesAdministrador reportes = new VentanaReportesAdministrador();
        reportes.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        modificarEstadoBotonesPanelOpciones(true);
        panelModificarRutas.setVisible(false); 
        lblTitulo2.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNombreActionPerformed
        // TODO add your handling code here:
         if(ManejadorError.verificarCampo(cajaTextoNuevoNombreRuta.getText())){
                try{
                    
                    String nombreR = cajaTextoNuevoNombreRuta.getText();
                   
                    //enlace.crearDestino(codDest, nombreDest, tarifa);
                    
                    JOptionPane.showMessageDialog(this, MensajesErrores.NOMBRE_RUTA_CAMBIADO);
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, MensajesErrores.NO_SON_NUMEROS);                }
            }else{
                JOptionPane.showMessageDialog(this, MensajesErrores.DATOS_FALTANTES);
            }  
    }//GEN-LAST:event_btnGuardarNombreActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // TODO add your handling code here:
        if(ManejadorError.verificarCampo(cajaTextoNuevaTarifaPControl.getText()) && ManejadorError.verificarCampo(cajaTextoNuevoNombrePControl.getText())){
                try{
                    int tarifa = Integer.parseInt(cajaTextoNuevaTarifaPControl.getText());
                    String nombreNPC = cajaTextoNuevoNombrePControl.getText();
                    int codPC = Integer.parseInt((String)comboBoxPuntosControl.getSelectedItem());
                    
                    
                    JOptionPane.showMessageDialog(this, MensajesErrores.DATOS_GUARDADOS);
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, MensajesErrores.NO_SON_NUMEROS);                }
            }else{
                JOptionPane.showMessageDialog(this, MensajesErrores.DATOS_FALTANTES);
        }  
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void modificarEstadoBotonesPanelOpciones(boolean estado){
        btnCrearRutas.setEnabled(estado);
        btnModificarRutas.setEnabled(estado);
        btnCrearDestinos.setEnabled(estado);
        btnModificarDestinos.setEnabled(estado);
        btnModificarTarifaGlobal.setEnabled(estado);
        btnReportes.setEnabled(estado);
    }
    
    private void modificarTarifaGlobal(int tarifa){
        enlace.modificarTarifaGlobal(tarifa);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NuevoNombrePuntoControl;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCrearDestinos;
    private javax.swing.JButton btnCrearRutas;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnGuardarNombre;
    private javax.swing.JButton btnModificarDestinos;
    private javax.swing.JButton btnModificarRutas;
    private javax.swing.JButton btnModificarTarifaGlobal;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField cajaTextoDato1;
    private javax.swing.JTextField cajaTextoDato2;
    private javax.swing.JTextField cajaTextoDato3;
    private javax.swing.JTextField cajaTextoNuevaTarifaPControl;
    private javax.swing.JTextField cajaTextoNuevoNombrePControl;
    private javax.swing.JTextField cajaTextoNuevoNombreRuta;
    private javax.swing.JComboBox<String> comboBoxPuntosControl;
    private javax.swing.JComboBox<String> destinosDisponibles;
    private javax.swing.JLabel lblCajaTexto1;
    private javax.swing.JLabel lblCajaTexto2;
    private javax.swing.JLabel lblCajaTexto3;
    private javax.swing.JLabel lblCodigoPControl;
    private javax.swing.JLabel lblNuevaTarifaPuntoControl;
    private javax.swing.JLabel lblNuevoNombreRuta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelModificarRutas;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables

    private void desactivarPaneles() {
        panelDatos.setVisible(false);
        lblCajaTexto3.setVisible(false);
        cajaTextoDato3.setVisible(false);
        lblTitulo2.setVisible(false);   
        panelModificarRutas.setVisible(false);
    }
    
    private void activarComponentesPanelDatos(boolean estadoBtnAgregar, boolean estadoBtnAtras, boolean estadoBtnGuardar,boolean estadoLblCT1, boolean estadoLblCT2, boolean estadoLblCT3 , boolean estadoBtnCT1, boolean estadoBtnCT2, boolean estadoBtnCT3){
        btnAgregar.setVisible(estadoBtnAgregar);
        btnAtras.setVisible(estadoBtnAtras);
        btnGuardar.setVisible(estadoBtnGuardar);
        lblCajaTexto1.setVisible(estadoLblCT1);
        lblCajaTexto2.setVisible(estadoLblCT2);
        lblCajaTexto3.setVisible(estadoLblCT3);
        cajaTextoDato1.setVisible(estadoBtnCT1);
        cajaTextoDato2.setVisible(estadoBtnCT2);
        cajaTextoDato3.setVisible(estadoBtnCT3);
        lblTitulo2.setVisible(true);        
    }
}
